import Head from 'next/head';
import { signOut } from "firebase/auth";
import { auth } from '../firebase/clientApp';


export default function Home() {

  const handleClick = () => {
    signOut(auth).then(() => {
      console.log('IT WORKED')
    }).catch((error) => {
      console.log(error.message)
    });
  }
  return (
    <>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex items-center justify-center h-screen'>
        <button onClick={handleClick} className='p-6 bg-white'>Signout</button>
      </main>
    </>
  )
}
